%this script is to plot all the graps of the SEIR model
%s= (feature_normalization(s)+2)/4;
%e= (feature_normalization(e)+2)/4;
%i= (feature_normalization(i)+2)/4;
%r= (feature_normalization(r)+2)/4;
%d= (feature_normalization(d)+2)/4;
subplot(2, 3, 1);
	plot(1:iter,s);
	title("Suceptible");
	xlabel('Days');
ylabel('Population');
subplot(2, 3, 2);
	plot(1:iter,e);
	title("Exposed");
	xlabel('Days');
ylabel('Population');
subplot(2, 3, 3);
	plot(1:iter,i);
	title("Infected");
	xlabel('Days');
ylabel('Population');
subplot(2, 3, 4);
	plot(1:iter,r);
	title("Recovered");
	xlabel('Days');
ylabel('Population');
subplot(2, 3, 5);
	plot(1:iter,d);
	title("Dead");
	xlabel('Days');
ylabel('Population');
subplot(2, 3, 6);
	img = imread ('SEIR-schematic.jpg');
	imshow(img);
print("-dpng", "SEIR covid 19 model graph plot.png");
